accounts/urls.py
from django.urls import path

from .views import SignUpView, LoginView


urlpatterns = [
    path("signup/", SignUpView, name="signup"),
    path("login/", LoginView.as_view(), name="login")
]

django_app/urls.py
from django.urls import path

from . import views
from .views import SignUpView

app_name = 'django_app'

urlpatterns = [
    path('', views.dashboard, name='dashboard'),
    path('stockinfo/', views.stockInfo, name='stockInfo'),
    path('news/', views.news_list, name='news'),
    path('add_to_favourites/<int:stock_id>/', views.add_to_favourites, name='add_to_favourites'),
    path('remove_from_favourites/<int:stock_id>/', views.remove_from_favourites, name='remove_from_favourites'),
    path('favourites/', views.favourites, name='favourites'),
    path('search/', views.search, name='search'),
    path('predict/<str:ticker>/<str:days>/', views.predict, name='predict'),
    path('stock_prediction/<str:ticker>/<int:days>/',views.stock_prediction_view, name='stock_prediction_view'),
]

django_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('', include('django_app.urls', namespace='django_app')),
    path("admin/", admin.site.urls),
    path("accounts/", include("accounts.urls")),
    path("accounts/", include("django.contrib.auth.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

django_app/models.py
from django.contrib.auth.models import User
from django.db import models


class Stock(models.Model):
    symbol = models.CharField(max_length=10)
    name = models.CharField(max_length=100)


class Favourite(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    stock = models.ForeignKey(Stock, on_delete=models.CASCADE)

django_app/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class SignupForm(UserCreationForm):
    email = forms.EmailField(max_length=254, help_text='Required. Inform a valid email address.')

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2', ]


class StockSearch(forms.Form):
    q = forms.CharField(label='', widget=forms.TextInput(
        attrs={'class': 'form-control me-2', 'type': 'search', 'placeholder': 'Stock Symbol', 'aria-label': 'Search'}))


class SearchForm(forms.Form):
    TickerName = forms.CharField(max_length=100, required=True, label='Stock Symbol')
    NumberofDays = forms.IntegerField(required=True, label='Prediction Days')

django_app/views.py
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from django.template.loader import render_to_string

import json
from django.urls import reverse_lazy, reverse
from urllib import request
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.template import RequestContext
from django.views import View, generic
from django.contrib.auth.decorators import login_required, user_passes_test
from .forms import StockSearch, SignupForm, SearchForm
from django.contrib.auth import authenticate, login, logout
from .models import Stock, Favourite
from django.shortcuts import redirect

from plotly.offline import plot
import plotly.graph_objects as go
import plotly.express as px
from plotly.graph_objs import Scatter

import pandas as pd
import numpy as np

import yfinance as yf
import datetime as dt

from accounts.models import UserProfile
from .utils import get_news

from sklearn.tree import DecisionTreeRegressor
from sklearn import preprocessing
from sklearn.model_selection import train_test_split


# Create your views here.


# Dashboard when Server loads
def dashboard(request):
    request.session['views'] = request.session.get('views', 0) + 1
    # Left Card Plot
    # Here we used yf.download function
    data = yf.download(
        # passes the ticker
        tickers=['AAPL', 'AMZN', 'QCOM', 'META', 'NVDA', 'GOOGL', 'UBER', 'TSLA'],

        group_by='ticker',

        threads=True,  # Set thread value to true

        # used for access data[ticker]
        period='1mo',
        interval='1d'

    )

    data.reset_index(level=0, inplace=True)

    fig_left = go.Figure()
    fig_left.add_trace(
        go.Scatter(x=data['Date'], y=data['AAPL']['Adj Close'], name="AAPL")
    )
    fig_left.add_trace(
        go.Scatter(x=data['Date'], y=data['AMZN']['Adj Close'], name="AMZN")
    )
    fig_left.add_trace(
        go.Scatter(x=data['Date'], y=data['QCOM']['Adj Close'], name="QCOM")
    )
    fig_left.add_trace(
        go.Scatter(x=data['Date'], y=data['META']['Adj Close'], name="META")
    )
    fig_left.add_trace(
        go.Scatter(x=data['Date'], y=data['NVDA']['Adj Close'], name="NVDA")
    )
    fig_left.add_trace(
        go.Scatter(x=data['Date'], y=data['GOOGL']['Adj Close'], name="GOOGL")
    )
    fig_left.add_trace(
        go.Scatter(x=data['Date'], y=data['UBER']['Adj Close'], name="UBER")
    )
    fig_left.add_trace(
        go.Scatter(x=data['Date'], y=data['TSLA']['Adj Close'], name="TSLA")
    )
    fig_left.update_layout(paper_bgcolor="#14151b", plot_bgcolor="#14151b", font_color="white")

    plot_div_left = plot(fig_left, auto_open=False, output_type='div')

    #  To show recent stocks

    df1 = yf.download(tickers='AAPL', period='1d', interval='1d')
    df2 = yf.download(tickers='AMZN', period='1d', interval='1d')
    df3 = yf.download(tickers='QCOM', period='1d', interval='1d')
    df4 = yf.download(tickers='META', period='1d', interval='1d')
    df5 = yf.download(tickers='NVDA', period='1d', interval='1d')
    df6 = yf.download(tickers='GOOGL', period='1d', interval='1d')
    df7 = yf.download(tickers='UBER', period='1d', interval='1d')
    df8 = yf.download(tickers='TSLA', period='1d', interval='1d')


    df1.insert(0, "Ticker", "AAPL")
    df2.insert(0, "Ticker", "AMZN")
    df3.insert(0, "Ticker", "QCOM")
    df4.insert(0, "Ticker", "META")
    df5.insert(0, "Ticker", "NVDA")
    df6.insert(0, "Ticker", "GOOGL")
    df7.insert(0, "Ticker", "UBER")
    df8.insert(0, "Ticker", "TSLA")


    df = pd.concat([df1, df2, df3, df4, df5, df6, df7, df8], axis=0)
    df.reset_index(level=0, inplace=True)
    df.columns = ['Date', 'Ticker', 'Open', 'High', 'Low', 'Close', 'Adj_Close', 'Volume']
    convert_dict = {'Date': object}
    df = df.astype(convert_dict)
    df.drop('Date', axis=1, inplace=True)

    json_records = df.reset_index().to_json(orient='records')
    recent_stocks = []
    recent_stocks = json.loads(json_records)

    #  Page Render section
    return render(request, 'django_app/dashboard.html', {
        'plot_div_left': plot_div_left,
        'recent_stocks': recent_stocks,
        'views': request.session['views']
    })


@login_required
def predict(request):
    response = HttpResponse()
    heading1 = '<p>' + 'PREDICT PAGE:' + '</p>'
    response.write(heading1)

    return response


@login_required
def stockInfo(request):
    # Load Ticker Table
    ticker_df = pd.read_csv('django_app/Data/new_tickers.csv')

    # Create or update Stock objects for each stock in the DataFrame
    # for index, row in ticker_df.iterrows():
    # Stock.objects.update_or_create(symbol=row['Symbol'], name=row['Name'])

    # Get the query (if it exists)
    query = request.GET.get('q')
    no_results = False

    if query:
        # Filter the DataFrame based on the query
        ticker_df = ticker_df[ticker_df['Symbol'].str.contains(query, case=False)]

        if ticker_df.empty:
            no_results = True

    ticker_list = ticker_df.to_dict('records')

    # Get the user's favourite stocks
    favourite_stocks = Favourite.objects.filter(user=request.user).values_list('stock_id', flat=True)

    # Add a 'favourite' attribute to each stock in the ticker list
    for i in ticker_list:
        i['favourite'] = i['id'] in favourite_stocks

    # Set up pagination - 18 rows per page
    page = request.GET.get('page', 1)
    paginator = Paginator(ticker_list, 18)

    try:
        tickers = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer, deliver first page.
        tickers = paginator.page(1)
    except EmptyPage:
        # If page is out of range, deliver last page of results.
        tickers = paginator.page(paginator.num_pages)

    # Create an instance of the form
    form = StockSearch(request.GET)

    return render(request, 'django_app/ticker.html', {
        'ticker_list': tickers,
        'no_results': no_results,
        'form': form
    })


@login_required
def add_to_favourites(request, stock_id):
    stock = Stock.objects.get(id=stock_id)
    Favourite.objects.create(user=request.user, stock=stock)
    return JsonResponse({'success': True})


@login_required
def remove_from_favourites(request, stock_id):
    stock = Stock.objects.get(id=stock_id)
    Favourite.objects.filter(user=request.user, stock=stock).delete()
    return JsonResponse({'success': True})


class SignUpView(generic.CreateView):
    form_class = SignupForm
    success_url = reverse_lazy('django_app/login')  # After signing up, redirect to login page
    template_name = 'django_app/registration/signup.html'


def login_here(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(username=username, password=password)
        if user:
            if user.is_active:
                login(request, user)
                return HttpResponseRedirect(reverse('django_app:dashboard'))
            else:
                return HttpResponse('Your account is disabled')
        else:
            return HttpResponse('Login details are incorrect')
    else:
        return render(request, 'django_app/registration/login.html')


@login_required
def logout_here(request):
    logout(request)
    return HttpResponseRedirect(reverse('django_app:dashboard'))


@login_required
def favourites(request):
    # Get the user's favourite stocks
    favouriteStocks = Favourite.objects.filter(user=request.user).select_related('stock')

    page = request.GET.get('page', 1)
    paginator = Paginator(favouriteStocks, 18)

    try:
        favourite_stocks = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer, deliver first page.
        favourite_stocks = paginator.page(1)
    except EmptyPage:
        # If page is out of range (e.g. 9999), deliver last page of results.
        favourite_stocks = paginator.page(paginator.num_pages)

    return render(request, 'django_app/favourites.html', {
        'favourite_list': favourite_stocks
    })


# News API Section
def news_list(request):
    user = request.user if request.user.is_authenticated else None
    news_data = get_news(user)
    return render(request, 'django_app/news_API.html', {'news_data': news_data})


def search(request):
    searched_stock = None
    if request.method == 'POST':
        form = SearchForm(request.POST)
        if form.is_valid():
            searched_stock = form.cleaned_data['TickerName']
            ticker = form.cleaned_data['TickerName']
            days = form.cleaned_data['NumberofDays']

            # Check if the number of days is within the valid range
            if 0 <= days <= 365:
                return redirect('django_app:stock_prediction_view', ticker=ticker, days=days)
            else:
                # Handle invalid days
                return render(request, 'django_app/Input_Days_Error.html',
                              {'error': "Input days must be between 0 and 365."})
    else:
        form = SearchForm()
    return render(request, 'django_app/search.html', {'form': form, 'searched_stock': searched_stock})


def validate_ticker(ticker_input):
    df = pd.read_csv('django_app/Data/new_tickers.csv')
    symbols_list = df['Symbol'].tolist()
    valid_tickers = symbols_list
    # tickers are all uppercase
    ticker_upper_value = ticker_input.upper()
    return ticker_upper_value in valid_tickers


def download_data(ticker_value):
    try:
        df = yf.download(tickers=ticker_value, period='1d', interval='1m')
        print(f"{ticker_value} downloaded")
        return df
    except Exception as e:
        print(e)  # Log error
        return


def perform_prediction(ticker_value, forecast, last_date):
    pred_dict = {"Date": [], "Prediction": []}
    start_date = pd.to_datetime(last_date)
    for i in range(len(forecast)):

django_app/templates/django_app/Input_Days_Error.html
{% extends 'django_app/base.html' %}
{% load static %}

{% block title %}
    ERROR!
{% endblock %}

{% block body_block %}
    <div class="container-fluid pt-4 px-4">
        <div class="row g-4">
            <div class="col-sm-12 col-xl-12">
                <div class="bg-secondary text-center rounded p-4">
                    <div class="d-flex align-items-center justify-content-between mb-4">
                            <h3 class="mb-0 align-items-center" style="color: red;">The Days input is incorrect!</h3>
                    </div>
                    {% if error %}
                        <h6 class="d-flex">{{ error }}</h6>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
{% endblock %}

django_app/templates/django_app/Input_Days_Greater_Than_365.html
{% extends "django_app/base.html" %}

{% block title %}Input Days Greater than 365{% endblock %}

{% block content %}
<h2>The Input Days is Greater than 365!</h2>

<div class="invalid-ticker-images">

</div>
{% endblock %}

django_app/templates/django_app/Input_Days_Less_Than_Zero.html
{% extends "django_app/base.html" %}

{% block title %}Input Days Greater than 365{% endblock %}

{% block content %}
<h2>The Input Days is Less Than 0!</h2>

<div class="invalid-ticker-images">

</div>
{% endblock %}

django_app/templates/django_app/TIcker_Unfounded.html
{% extends 'django_app/base.html' %}
{% load static %}

{% block title %}
    ERROR!
{% endblock %}

{% block body_block %}
    <div class="container-fluid pt-4 px-4">
        <div class="row g-4">
            <div class="col-sm-12 col-xl-12">
                <div class="bg-secondary text-center rounded p-4">
                    <div class="d-flex align-items-center justify-content-between mb-4">
                            <h3 class="mb-0 align-items-center" style="color: red;">Invalid Stock Name!</h3>
                    </div>
                    {% if error %}
                        <h6 class="d-flex">{{ error }}</h6>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
{% endblock %}

django_app/templates/django_app/Ticker_Unfounded.html
{% extends "django_app/base.html" %}

{% block title %}The Ticker is Unfounded{% endblock %}

{% block content %}
<h2>The Ticker is Unfounded!</h2>

<div class="invalid-ticker-images">

</div>
{% endblock %}

django_app/templates/django_app/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <title> {% block title %} {% endblock %}</title>
    <meta content="width=device-width, initial-scale=1.0" name="viewport">
    <meta content="" name="keywords">
    <meta content="" name="description">

    <!-- Google Web Fonts -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Open+Sans:wght@400;600&family=Roboto:wght@500;700&display=swap" rel="stylesheet">

    <!-- Icon Font Stylesheet -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0/css/all.min.css" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.1/font/bootstrap-icons.css" rel="stylesheet">

    <!-- Customized Bootstrap Stylesheet -->
    <link href="{% static 'django_app/css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Stylesheet -->
    <link href="{% static 'django_app/css/style.css' %}" rel="stylesheet">
</head>

<body>
    <div class="container-fluid position-relative d-flex p-0">
        <!-- Spinner Start -->
        <div id="spinner" class="show bg-dark position-fixed translate-middle w-100 vh-100 top-50 start-50 d-flex align-items-center justify-content-center">
            <div class="spinner-border text-success" style="width: 3rem; height: 3rem; color: #4ADE80;" role="status">
                <span class="sr-only">Loading...</span>
            </div>
        </div>
        <!-- Spinner End -->


        <!-- Sidebar Start -->
        <div class="sidebar pe-4 pb-3">
            <nav class="navbar bg-secondary navbar-dark">
                <a href="../.." class="navbar-brand mx-4 mb-3">
                    <h3 class="text-primary icon-color">Stocks</h3>
                </a>
                <div class="d-flex align-items-center ms-4 mb-4">
                    <div class="position-relative">
                        {% if user.is_authenticated %}
                            <img class="rounded-circle" src="{{ user.profile.avatar.url }}" alt="" style="width: 40px; height: 40px;">
                        {% else %}
                             <img class="rounded-circle" src="{% static 'django_app/image/user.png' %}" alt="" style="width: 40px; height: 40px;">
                        {% endif %}
                        <div class="bg-success rounded-circle border border-2 border-white position-absolute end-0 bottom-0 p-1"></div>
                    </div>
                    <div class="ms-3">
                        <h6 class="mb-0">Welcome</h6>
                            {% if user.is_authenticated %}
                                <span> {{ user.username }}</span>
                            {% else %}
                                <span>Guest</span>
                            {% endif %}
                    </div>
                </div>
                <div class="navbar-nav w-100">
                    {% if user.is_authenticated %}
                        <a href="{% url 'django_app:dashboard'%}" class="nav-item nav-link {% if request.resolver_match.url_name == 'dashboard' %}active{% endif %}" ><i class="fa fa-home me-2"></i>Dashboard</a>
                        <a href="{% url 'django_app:search'%}" class="nav-item nav-link {% if request.resolver_match.url_name == 'search' %}active{% endif %}" ><i class="fa fa-search me-2"></i>Prediction</a>
                        <a href="{% url 'django_app:stockInfo'%}" class="nav-item nav-link {% if request.resolver_match.url_name == 'stockInfo' %}active{% endif %}"><i class="fa fa-info me-2"></i>Stock Info</a>
                        <a href="{% url 'django_app:favourites'%}" class="nav-item nav-link {% if request.resolver_match.url_name == 'favourites' %}active{% endif %}"><i class="fa fa-heart me-2"></i>Favourites</a>
                        <a href="{% url 'django_app:news'%}" class="nav-item nav-link {% if request.resolver_match.url_name == 'news' %}active{% endif %}"><i class="fa fa-list-alt me-2"></i>News</a>
                    {% else %}
                        <a href="{% url 'django_app:dashboard'%}" class="nav-item nav-link {% if request.resolver_match.url_name == 'dashboard' %}active{% endif %}" ><i class="fa fa-home me-2"></i>Dashboard</a>
                        <a href="{% url 'django_app:news'%}" class="nav-item nav-link {% if request.resolver_match.url_name == 'news' %}active{% endif %}"><i class="fa fa-list-alt me-2"></i>News</a>
                    {% endif %}

                </div>

            </nav>
        </div>
        <!-- Sidebar End -->


        <!-- Content Start -->
        <div class="content">
            <!-- Navbar Start -->
            <nav class="navbar navbar-expand bg-secondary navbar-dark sticky-top px-4 py-0">
                <a href="../.." class="navbar-brand d-flex d-lg-none me-4">
{#                    <h2 class="text-primary mb-0"><i class="fa fa-user-edit"></i></h2>#}
                </a>
                <a href="#" class="sidebar-toggler flex-shrink-0">
                    <i class="fa fa-bars icon-color"></i>
                </a>

                <div class="navbar-nav align-items-center ms-auto">
                    <div class="nav-item dropdown">
                        <a href="#" class="nav-link dropdown-toggle" data-bs-toggle="dropdown">
                            {% if user.is_authenticated %}
                                <img class="rounded-circle me-lg-2" src="{{ user.profile.avatar.url }}" alt="" style="width: 40px; height: 40px;">
                                <span class="d-none d-lg-inline-flex">{{ user.username }}</span>
                            {% else %}
                                <img class="rounded-circle me-lg-2" src="{% static 'django_app/image/user.png' %}" alt="" style="width: 40px; height: 40px;">
                                <span class="d-none d-lg-inline-flex">Guest</span>
                            {% endif %}

                        </a>
                        <div class="dropdown-menu dropdown-menu-end bg-secondary border-0 rounded-0 rounded-bottom m-0">
                            {% if user.is_authenticated %}
                                <a href="{% url 'logout'%}" class="dropdown-item">Logout</a>
                            {% else %}
                                <a href="{% url 'login'%}" class="dropdown-item">Login</a>
                            {% endif %}

                        </div>
                    </div>
                </div>
            </nav>
            <!-- Navbar End -->

            {% block body_block %} *** {% endblock %}

        </div>
        <!-- Content End -->

    </div>

    <!-- JavaScript Libraries -->
    <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.bundle.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/3.8.0/chart.min.js" integrity="sha512-sW/w8s4RWTdFFSduOTGtk4isV1+190E/GghVffMA9XczdJ2MDzSzLEubKAs5h0wzgSJOQTRYyaz73L3d6RtJSg==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>

    <!-- Template Javascript -->
    <script src="{% static 'django_app/js/main.js' %}"></script>
</body>

</html>

django_app/templates/django_app/base_auth.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{% block title %}Stock Prediction{% endblock %}</title>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdn.materialdesignicons.com/4.8.95/css/materialdesignicons.min.css">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
    <link rel="stylesheet" href="{% static 'django_app/css/style_auth.css' %}">

    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
    <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"></script>

</head>
<body>
    <main>
        {% block content %}
        {% endblock %}
  </main>
</body>
</html>

django_app/templates/django_app/dashboard.html
{% extends 'django_app/base.html' %}
{% load static %}

{% block title %}
    Dashboard
{% endblock %}

{% block body_block %}
    <!-- Active Stock Section Start -->
    <div class="container-fluid pt-4 px-4">
        <div class="row g-4">
            <div class="col-sm-12 col-xl-12">
                <div class="bg-secondary text-center rounded p-4">
                    <div class="d-flex align-items-center justify-content-between mb-4">
                        <h6 class="mb-0">Stock Chart View</h6>
                        <h6>You have viewed this page {{ views }} times.</h6>
                    </div>
                        <!-- plotting is done here -->
                    {% block Left_Plot %}
                        {% autoescape off %}
                            {{ plot_div_left }}
                        {% endautoescape %}
                    {% endblock Left_Plot %}
                    <!-- plotting ends -->
                </div>
            </div>
        </div>
    </div>
    <!-- Active Stock Section End -->


    <!-- Recent Sales Start -->
    <div class="container-fluid pt-4 px-4">
            <div class="bg-secondary text-center rounded p-4">
                <div class="d-flex align-items-center justify-content-between mb-4">
                    <h6 class="mb-0">Stock List View</h6>
                    <a href="https://finance.yahoo.com/trending-tickers" class="show-all-button" target="_blank">Show All</a>
                </div>
                <div class="table-responsive">
                    <!-- Recent stocks data here-->
                    <table class="table text-start align-middle table-bordered table-hover mb-0">
                        <thead>
                            <tr class="text-white">
                                <th scope="col">Stock</th>
                                <th scope="col">Open</th>
                                <th scope="col">High</th>
                                <th scope="col">Low</th>
                                <th scope="col">Close</th>
                                <th scope="col">Adj. Close</th>
                                <th scope="col">Volume</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% if recent_stocks %}
                            {% for i in recent_stocks %}
                            <tr>
                                <td>{{i.Ticker}}</td>
                                <td>{{i.Open}}</td>
                                <td>{{i.High}}</td>
                                <td>{{i.Low}}</td>
                                <td>{{i.Close}}</td>
                                <td>{{i.Adj_Close}}</td>
                                <td>{{i.Volume}}</td>
                            </tr>
                            {% endfor %}
                            {% endif %}
                        </tbody>
                    </table>
                </div>
            </div>
    </div>
    <!-- Recent Sales End -->

{% endblock %}

django_app/templates/django_app/favourites.html
{% extends 'django_app/base.html' %}
{% block title %}
    Favourites
{% endblock %}
{% block body_block %}
    <div class="container-fluid  pt-4 px-4">
        <div class="bg-secondary text-center rounded p-4">
            <div class="d-flex align-items-center justify-content-between mb-4">
                <h6 class="mb-0">Your Favourite Stocks</h6>
            </div>
            <div class="table-responsive">
                <table class="table text-start align-middle table-bordered table-hover mb-0">
                    <thead>
                        <tr class="text-white">
                            <th scope="col">Stock Symbol</th>
                            <th scope="col">Stock Name</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for favourite in favourite_list %}
                            <tr>
                                <td>{{ favourite.stock.symbol }}</td>
                                <td>{{ favourite.stock.name }}</td>
                            </tr>
                        {% empty %}
                            <tr>
                                <td colspan="2">You have no favourite stocks.</td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
{% endblock %}

django_app/templates/django_app/news_API.html
{% extends 'django_app/base.html' %}
{% load static %}

{% block title %}
    News
{% endblock %}


{% block body_block %}
   <div class="container-fluid pt-4 px-4">
    <div class="row g-4">
        <div class="col-sm-12 col-xl-12">
            <div class="bg-secondary rounded p-4">
                {% for news_item in news_data.data %}
                    <div class="card mb-3 bg-inherit">
                        <div class="row g-0">
                            <div class="col-md-3">
                                <img src="{{ news_item.image_url }}" alt="Image" class="img-fluid">
                            </div>
                            <div class="col-md-8">
                                <div class="card-body">
                                    <h5 class="card-title">{{ news_item.title }}</h5>
                                    <p class="card-text">{{ news_item.description }}</p>
                                    <p class="card-text"><small class="text-muted">{{ news_item.published_at }}</small></p>
                                    <a href="{{ news_item.url }}" target="_blank" class="btn btn-success add-to-favourites">Read More</a>
                                </div>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>
    </div>
</div>

{% endblock %}

django_app/templates/django_app/test.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>